### PR TITLE
Jb narrative modals

### PR DESCRIPTION
**Pull request by jbevis**
This PR will add the narrative notifications as modals to certain steps in a user's path upon their first use of the site.

To test changes please review on 
https://cfgov-refresh-dev.herokuapp.com/mmt-my-money-calendar

In order to trigger the modals, clear all storage from the site. They will only run on a user's first use of the app.

To do:

In google chrome

- right click screen > inspect

Screen Shot 2020-06-30 at 11 23 53 AM

- navigate to application tab
- click 'Clear site data'

Screen Shot 2020-06-30 at 11 24 19 AM

- refresh app, and step through wizard as usual
- Narrative notifications will launch:

- 1: First arrival to calendar after entering starting balance
- 2: After entering first income or expense
- 3: First visit to SNAP benefit form
- 4: First visit to Fix-it Strategy page.

### CODE REVIEW

**Comment by jbevis** [comment]
Closes #51

**Comment by jbevis** [comment]
@shubhi-raft has given the thumbs up for this to be merged.

There are some minor copy updates that are still pending, but that can be tracked and handled with a new issue. I'd like to get the logic/functional changes merged in, and the copy with be a simple forthcoming update.

@MissyM2 or @BarakStout please review and merge at earliest convenience.

Closes #51

**Comment by jbevis** [comment]
@MissyM2 @BarakStout 

Latest copy updates have been pushed and deployed to dev.

Should be ready for a merge...

**Comment by MissyM2** [comment]
The notifications work as requested.

**Pull request merged**
