### PR TITLE
Initial calendar view

### PR DESCRIPTION
**Pull request by mgreen-simplethread**
Adds a route that renders the returning user landing view, a calendar displaying the user's transactions for the current month, with chronological navigation. 

The cash flow event model has been updated with more robust IndexedDB persistence methods, and the cash flow store now creates individually editable copies of recurring events at their specified intervals upon saving. It includes business logic to prevent duplicate recurrences from being saved, and it also has an IDB compound index that enforces uniqueness and throws exceptions should all else fail.

I've also added several additional IDB indices that allow querying and sorting cash flow events based on fields other than date and ID.

Screenshot 2020-02-05 22 15 36

There is a basic form for adding income and expense events, but currently no interface for specifying recurrence rules. This is a somewhat more complicated feature that I plan to add this week. This particular form is just here for development purposes, but I'll be able to reuse most if not all of the field components on the actual forms we build for users.

Screenshot 2020-02-10 07 59 26

### CODE REVIEW

**Comment by mgreen-simplethread** [comment]
@meissadia @PatrickGoRaft I've deployed this branch's changes up to the Heroku staging server: https://cfgov-refresh-staging.herokuapp.com/mmt-my-money-calendar/calendar.

It's running on a single Free dyno, so the first load is going to be slow as it spins up the entire backend app. Please let me know if any static assets fail to load for you. I've been having issues with the way Heroku requires Django apps to handle that, and it won't be an issue anywhere else we deploy this app. I believe I've figured out the problem and fixed it, though.

I see one issue already - the app loads with a balance of $NaN. Fixing that now. You should be able to add income and expenses using the form I created, but the DB seed data isn't currently available because NODE_ENV isn't "development" up there.

**Comment by PatrickGoRaft** [comment]
I'm having issues accessing the app via that URL. Do I need some special access ?

**Comment by mgreen-simplethread** [comment]
> @mgreen-simplethread would it be possible to update the logic to default to "development" if NODE_ENV isn't implicitly set? @meissadia thoughts?

It already does in the webpack config. Deploying to Heroku sets it to "production" by default, but I should be able to update the app's environment variables. I'll try that now.

**Comment by mgreen-simplethread** [comment]
> I'm having issues accessing the app via that URL. Do I need some special access ?

I had basic auth enabled back when it was only me and Missy using staging. I've just disabled it, so you should be able to access it now. Sorry about that!

**Comment by PatrickGoRaft** [comment]
You already made note of static assets failing to load due to the environment in which they're deployed. I just wanted to make sure those broken references  are the following:
Screen Shot 2020-02-13 at 10 46 42 AM

**Comment by mgreen-simplethread** [comment]
> You already made note of static assets failing to load due to the environment in which they're deployed. I just wanted to make sure those broken references are the following:
> Screen Shot 2020-02-13 at 10 46 42 AM

Yeah, those aren't part of our app, and they also fail locally. I think there is a separate setup step for fonts because they're licensed

**Comment by mgreen-simplethread** [comment]
@PatrickGoRaft The static asset failures I mentioned before were more widespread. If they were happening, the calendar wouldn't look like a calendar.

**Comment by meissadia** [comment]
@mgreen-simplethread I'm unable to create incomes/expenses.  Seeing the following in the console:

Screen Shot 2020-02-13 at 10 15 26 AM

**Comment by meissadia** [comment]
@mgreen-simplethread While scrolling through the months, I notice that some do not display a calendar:

December, 2018
December, 2019
January, 2021
January, 2022
January, 2023

**Comment by mgreen-simplethread** [comment]
> @mgreen-simplethread While scrolling through the months, I notice that some do not display a calendar:
> 
> December, 2018
> December, 2019
> January, 2021
> January, 2022
> January, 2023

Fixed - I had kind of a naive implementation that couldn't handle the end week number being less than the start week, as happens in December (and when I was showing December dates leading up to the first week in January). I fixed the issue by getting the difference in weeks between the end of the month and the beginning, then just counting up to that number in the loop, rounded up.

**Comment by mgreen-simplethread** [comment]
> @mgreen-simplethread I'm unable to create incomes/expenses. Seeing the following in the console:
> 
> Screen Shot 2020-02-13 at 10 15 26 AM

This is fixed too. I forgot to send this comment on Friday.

**Pull request merged**
