### PR TITLE
Replace date library

### PR DESCRIPTION
**Pull request by mgreen-simplethread**
This PR addresses a bug I noticed a couple weeks ago. Luxon, the date library I was using, does not respect locale settings and always wants the first day of the week to be Monday. For most countries besides the US, that works fine, but it was causing my US-friendly calendar with weeks beginning on Sunday to report the wrong weekday for all of its dates.

I ended up needing to rip out Luxon and replace it with DayJS, which ended up being a good thing anyway. DayJS has an API that's compatible with Moment.js, but it's a lot smaller than both Moment and Luxon, so it'll save us some bundle weight in addition to respecting locale specific week start days.

I could use a little help testing this change out on staging, just to be sure that the calendar still works correctly, and events can be created and deleted without incident.

### CODE REVIEW

**Comment by meissadia** [comment]
- **Recurring Events:** Adding a Weekly Income starting 3/9/20 (Monday) creates the recurring event on each Friday.  I would expect the event to recur on the same day of the week that the initial event was created.  This could just be how the business logic is designed.
Screen Shot 2020-03-09 at 7 46 50 PM

**Comment by meissadia** [comment]
-  **Recurring Events:** Adding a recurring Semi-Monthly Income (March 5th, 25th) adds it incorrectly in April (3rd, 24th).  Though this seems to simply be favoring business days when a recurrence date falls on a weekend.
Screen Shot 2020-03-09 at 9 30 43 PM
Screen Shot 2020-03-09 at 9 30 50 PM

**Comment by meissadia** [comment]
-  **Recurring Events:** Unable to delete 'This and future recurrences' 
Screen Shot 2020-03-09 at 7 43 31 PM

**Comment by meissadia** [comment]
-  **Date Selection:**  The current day is not highlighted when I hit the "Today" button unless I switch to a different month first, then hit the "Today" button. 
today-not-highlighted

**Comment by meissadia** [comment]
- **Date Selection:** The currently selected day is not highlighted on the calendar, though the transaction summary shows the correct data.  Shown in previous comment's gif.

**Comment by meissadia** [comment]
Days of some months don't seem to be styled correctly. 

**January 2020:** the 26th - 31st are greyed out but February 1st is black.

Screen Shot 2020-03-09 at 9 16 10 PM

**December 2019:** the 29th - 31st are greyed out but January 1st - 4th are black.

Screen Shot 2020-03-09 at 9 17 16 PM

**Comment by mgreen-simplethread** [comment]
> * **Recurring Events:** Adding a recurring Semi-Monthly Income (March 5th, 25th) adds it incorrectly in April (3rd, 24th).  Though this seems to simply be favoring business days when a recurrence date falls on a weekend.
> 
> Screen Shot 2020-03-09 at 9 30 43 PM
> 
> Screen Shot 2020-03-09 at 9 30 50 PM

Semi-monthly recurrence does favor business days. I set it to do that deliberately, since IME that's when payroll companies set their pay days in practice. I thnk you're right that it might be confusing for users though. I might want to find a way to explain that that's how it's working.

**Comment by mgreen-simplethread** [comment]
> * **Recurring Events:** Unable to delete 'This and future recurrences'
> 
> Screen Shot 2020-03-09 at 7 43 31 PM

This is fixed. 

> * **Date Selection:**  The current day is not highlighted when I hit the "Today" button unless I switch to a different month first, then hit the "Today" button.
>   today-not-highlighted

I can't replicate this on staging or locally. There could be a caching issue going on with the service worker that I need to investigate instead, where it's giving you a stale stylesheet. I'm going to kill the service worker on stage for now so that we can focus on QA first.

**Comment by mgreen-simplethread** [comment]
@meissadia Correction on the date selection issue - I was able to replicate it. It was caused by an optimization I'd made earlier that renders a simplified calendar square if the store has no financial transactions in it. It wasn't rendering with the right classname to give it a border when it was selected. I have a fix going up to staging now.

I've also disabled the service worker for the time being, so there will be less cache weirdness. The oddly greyed out calendar days was happening to me not too long ago locally, and completely flushing my stored app data fixed it IIRC.

Even with the service worker disabled, you'll need to unregister it locally in order to make it stop caching things. In devtools, go to Application > Service Workers, and click the Stop and Unregister links in that order. Then go to Clear Storage and click the Clear site data button and refresh the page. It'll wipe everything the app has stored locally and reload it from the server.

**Comment by mgreen-simplethread** [comment]
> * **Recurring Events:** Adding a Weekly Income starting 3/9/20 (Monday) creates the recurring event on each Friday.  I would expect the event to recur on the same day of the week that the initial event was created.  This could just be how the business logic is designed.
> 
> Screen Shot 2020-03-09 at 7 46 50 PM

Weekly recurrence days are fixed on stage now. I had it defaulting to Friday, but the day the event occurs on should have been overriding that default. No default is really needed with the way I've currently structured things, so it wasn't necessary to keep around at all.

**Comment by mgreen-simplethread** [comment]
I think the incorrectly highlighted calendar days were related to something I fixed while I was figuring out the date selection issue, btw. The boolean values I was using to flag events as in the current month were memoized using `useMemo`, but they really shouldn't have been since they were coming from MobX store observables which are already memoized. Making those into plain variables seems to have fixed it.

**Pull request merged**
