### PR TITLE
Update how SNAP benefits are displayed in UI

### LINKED ISSUE #52: Verify SNAP logic and integrate into UI
Verify SNAP logic and integrate into UI.  The way that SNAP income appears in the UI has not been determined, yet.

fyi @shubhi-raft @meissadia @RedNumberIX @LesliePerucci @omnipresent07 @MissyM2 

## Current behavior

-  SNAP income is treated as regular income in the app.  That is, for income balance calculations, SNAP is considered just like any other income.  In reality, this _income_ is actually a _benefit_ that may only be used for groceries.  It is a form of _restricted income_.  

## Expected behavior

-  Balances need to correctly reflect that SNAP income has been just used for groceries and the user needs to understand how much money they have available for their use from both _regular income_ and _SNAP benefit income_.

## Screenshots

__Current__
In this scenario, I added $100 for starting balance.  I added $250/week (on Fridays) for job income and $75/money for SNAP benefit income.  I added electricity $85/month on the 23rd and rent payment of $850 on the first of the month.  I **have not added any groceries** but,  my _SNAP benefit_ $75 has been applied to other bills.

Screen Shot 2020-06-15 at 9 12 40 AM

__Expected__

### PR DESCRIPTION
**Pull request by jbevis**
This PR will update the UI to better display SNAP benefits balance and not include it into the total balance.

Closes #52 (comment section)

NOTE: Has not been deployed to ```dev``` yet.

### CODE REVIEW

**Comment by MissyM2** [comment]
SNAP logic works properly.

**Comment by MissyM2** [comment]
@jbevis 
**Testing on Staging server/Safari**:  I tested a few new scenarios and came up with the following issue:

Steps:
- $0 starting balance
- $90 SNAP benefit added for July 1, 2020
- $25 weekly groceries on Fridays, starting July 3, 2020
- move to the first week that goes into the red:  week of July 20

**Current Outcome**:
- Calendar color should be green because, it was agreed that, if the regular balance is $0 or above, the calendar will be **green**.  In this case, the regular balance is $0, so the color is correct.
- The _Fix-it_ message appears, saying "You are going to be in the red!" with a _Weekly End Balance_ :-$10.00 The regular _Weekly End Balance_ should be $0 and the _Weekly SNAP End Balance_ should be $-10.00.  

**Expected Outcome**:
- The information on the _Fix It_ message should say _Weekly End Balance_ is $0. 
- Consider adding the _Weekly SNAP End Balance_ to this.
- Question:  Should the _Fix-It_ message be triggered under either circumstance?
Screen Shot 2020-06-26 at 12 06 55 PM

**Comment by jbevis** [comment]
@MissyM2 you raise some good points, but they fall outside the scope of this particular ticket. Especially since they include questions/considerations that have not been captured in the current issue.

This effort was just handling how SNAP income is calculated against non-snap income and the weekly totals are displayed in the UI.

I think your feedback should be captured in a new issue for the backlog that we can address later.

**Comment by jbevis** [comment]
Awaiting feedback, currently live on staging

**Comment by MissyM2** [comment]
I am taking my comments and opening a new issue, to be considered later, in the backlog.  This pr meets all the criteria.

**Pull request merged**
